### ISSUE TITLE
Implement properly `prove_score_generation`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/dusk-blindbid#23]
The function in subject still contains an `unimplemented!()`, as stated by the comment written by @CPerezz:

> TODO: Return the proof with a pre-computed PreprocessedCircuit and 

Unfortunately is not totally clear what are the steps involved, see discussion here: https://github.com/dusk-network/dusk-blindbid/pull/20/files#r450139621

Therefore this follow up bug, to finish properly the implementation.

**Comment by CPerezz** [comment]
This will still be on this shape until the impl of the ECC gate in plonk lands. Since this will trigger an API break and therefore, the code will need to be refactored.

**Comment by CPerezz** [comment]
That can be closed since we already addressed this in #53
