### ISSUE TITLE
Implement Score generation functionality

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-blindbid#6]
Since this is going to be a dependency used by `rusk`.

Does it make sense to implement here the logic to generate Scores?

@julesdesmit you're probably the one that will know this better.

**Comment by julesdesmit** [comment]
Yes, the score is generated as part of the blind bid function, should be on the document.

**Comment by CPerezz** [comment]
I was asking in terms of: Would be rust the one who computes the score? Or would be go? 
Since I can add this functionality here if rust has to be the one in charge of this.

Which doc are you referencing btw?

**Comment by julesdesmit** [comment]
Ah, it would definitely be Rust - it has been Rust in the past as well.

I'm referencing [this doc](https://github.com/dusk-network/dusk-blindbid/files/4621446/Proof_of_Blind_Bid.pdf)

**Comment by CPerezz** [comment]
Nice! Thanks a lot mate!

**Comment by CPerezz** [comment]
Reopening this since some things changed. And it needs to be re-done.
