### ISSUE TITLE
Test Score generation fn's against test vectors

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-blindbid#8]
We're currently waiting to obtain test vectors for BLS12_381 and the score generation function.

Once we have them, we should test that indeed we're computing what we expect.

**Comment by CPerezz** [comment]
Blocked until @khovratovich & @toghrulmaharramov  provide the test vectors for it.

**Comment by toghrulmaharramov** [comment]
I will speak to @khovratovich today and we will work on producing test vectors asap.
