### ISSUE TITLE
Implement custom annotation for the BidTree

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-blindbid#87]
We need a way to scan the tree in order to search for Bids. There are functions like `findBid` defined for the Bid Contract which would require that feature.

The problem is that we don't want to scan the whole tree and instead, we just want to check the valid Bids (to reduce the scanning time). This means that we basically need to filter out all of the expired/non-elegible bids. And to do so, we need a custom annotation implemented for the Bid Tree that allows us to do so.

This annotation simply has to return/scan through the subset of leaves that are elegible/non-expired.

**Comment by ZER0** [comment]
This will be solved by #86
